# https://prettier.io/docs/en/options.html
printWidth: 80

# Use .editorconfig settings
tabWidth: 2
useTabs: false

semi: true
singleQuote: true
quoteProps: as-needed
trailingComma: none
bracketSpacing: true
jsxBracketSameLine: true
arrowParens: avoid
proseWrap: always
